### ISSUE TITLE
Grunt-Sass Compressed output style + Autoprefixer breaks Sourcemaps

### ISSUE THREAD

**Issue by marcelosomers** [patternpack/patternpack#76]
By default, the `grunt-sass` task is using the `compressed` (i.e., minifed) output option. Something about this combined with Autoprefixer causes sourcemaps to break.

For example, the following code outputted by Sass (expanded style for readability, with no vendor prefixes):

``` css
.test {
  display: flex;
  align-items: stretch;
}

body {
  background: white;
}
```

Is referenced just fine, but when you add vendor prefixes in your final CSS file:

``` css
.test { 
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
  -webkit-align-items: stretch;
  -ms-flex-align: stretch;
  align-items: stretch;
}

body {
  background-color: white
}
```

The sourcemap offsets `body` by the number of additional vendor prefixes that get added (i.e., in this case, it references body 4 lines before it actually exists). This problem compounds itself with bigger stylesheets.

A simple fix I found was to use the `expanded` output style (for a temporary fix).

I believe the issue is around the sourcemap being initially generated by `grunt-sass`, but then PostCSS handles something related to the map as well, and they are not talking to each other.
